CREATE TABLE USUARIO(
    ID INT  NOT NULL AUTO_INCREMENT ,
    NOMBRE VARCHAR(30),
    APELLIDO VARCHAR(30),
    EMAIL VARCHAR(60),
    PASSW VARCHAR(40),
    FECHA DATETIME,

    CONSTRAINT PK_USUARIO PRIMARY KEY (ID) 
);


CREATE TABLE CATEGORIA(
    ID INT NOT NULL AUTO_INCREMENT ,
    NOMBRE VARCHAR(50),

    CONSTRAINT PK_CATEGORIA PRIMARY KEY(ID)
)ENGINE=InnoDb;

CREATE TABLE ENTRADA(
    ID INT NOT NULL AUTO_INCREMENT ,
    USUARIO_ID INT NOT NULL ,
    CATEGORIA_ID INT NOT NULL,
    TITULO VARCHAR(40),
    DESCRIPCION VARCHAR(100),
    FECHA DATE ,

    CONSTRAINT PK_ENTRADA PRIMARY KEY(ID),
    CONSTRAINT FK_ENTRADA_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
    CONSTRAINT FK_ENTRADA_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID)
);
